base_url = "https://example.com"
compile_sass = true
build_search_index = true

default_language = "ja"
title = "サイトのタイトル"
description = "サイトの<b>説明</b>です。"

[markdown]
highlight_code = true

[extra]
author = "ytyaru"
